title = "Riskiryhmä"
baseURL = "riski.com"
languageCode = "fi-FI"
theme = ["ananke"]
resourceDir = "../resources"
toc = true

DefaultContentLanguage = "fi"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.fi]
    title = "Riskiryhmä"
    weight = 1
    contentDir = "content/fi"
    # languageDirection = 'rtl' for Right-To-Left languages

 # [languages.fr]
 #   title = "Ananke Fr"
 #   weight = 2
 #   contentDir = "content/fr"
 # [languages.en]
 #   title = "Ananke En"
 #   weight = 3
 #   contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "    "
  author = ""
  favicon = ""
  site_logo = ""
  description = "Kulttuuria kaikille."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-gray"
  recent_posts_number = 3
  date_format = "2. January 2006"

# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"
